apiVersion: v1
kind: Service
metadata:
  name: api-feed
  labels:
    app: api-feed
spec:
  selector:
    app: api-feed
  ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
