apiVersion: v1
kind: Service
metadata:
  name: api-users
  labels:
    app: api-users
spec:
  selector:
    app: api-users
  ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
