version: "3.9"
services:
  reverseproxy:
    image: reverseproxy:latest
    build: "./udagram-reverseproxy"
  backend-user:
    image: udagram-api-user:latest
    build: "./udagram-api-users"
  backend-feed:
    image: udagram-api-feed:latest
    build: "./udagram-api-feed"
  frontend:
    image: udagram-frontend:bcupdated
    build: "./udagram-frontend"
