apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy
  labels:
    app: reverse-proxy
spec:
  selector:
    run: reverse-proxy
  ports:
    - name: "8080"
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP
