apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
  labels:
    app: reverse-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reverse-proxy
  template:
    metadata:
      labels:
        app: reverse-proxy
    spec:
      containers:
        - name: reverse-proxy
          image: epsilon1/reverse-proxy:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "2Gi"
              cpu: "250m"
            requests:
              memory: "1Gi"
              cpu: "200m"
          ports:
            - containerPort: 8080
