version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build_docker_images:
    docker:
      - image: cimg/node:18.0.0
    steps:
      - checkout
      - setup_remote_docker:
        docker-layer-caching: true
      - run:
          name: building docker images
          command: docker-compose -f ../docker-compose-build.yml build --parallel

workflows:
  build:
    jobs:
      - build_docker_images:
          version: "18"
          pkg-manager: npm
